modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "LGPL-3.0-or-later"

[[mods]]
modId = "langpatchconf"
version = "${version}"
displayName = "Enchantment Level Language Patch Config"
authors = "teddyxlandlee"
description = '''
Config extension for Enchlevel-LangPatch
'''
#logoFile = ""

[[dependencies.langpatchconf]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.langpatchconf]]
modId = "enchlevellangpatch"
mandatory = true
versionRange = "[1.2,)"
ordering = "NONE"
side = "BOTH"
